USE TODODB;

CREATE TABLE IF NOT EXISTS USER(ID VARCHAR(15),NAME VARCHAR(30),PRIMARY KEY (ID));
CREATE TABLE IF NOT EXISTS TODO(ID INT NOT NULL AUTO_INCREMENT,USERID VARCHAR(15),TEXT VARCHAR(200),COMPLETED BOOLEAN,FOREIGN KEY (USERID) REFERENCES USER(ID),PRIMARY KEY (ID));