version: "4"

services:
  db:
    image: mysql:5
    restart: always
    # command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./database/prod.env
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d:ro
      - mysql-data:/var/lib/mysql
    # ports:
    #   - "3306:3306"

  backend:
    image: todo-slackbot-server:1
    build: ./node-server
    restart: unless-stopped
    # ports:
    #   - 3000:3000
    env_file:
      - ./node-server/prod.env
    depends_on:
      - db

  tunnel:
    image: cloudflare/cloudflared:latest
    # network_mode: "host"
    env_file:
      - ./.env
    command: "tunnel --no-autoupdate run --token $TUNNEL_TOKEN"
    depends_on:
      - backend

volumes:
  mysql-data:
