version: "3.1"

services:
  db:
    image: mysql:5
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./init:/docker-entrypoint-initdb.d:ro
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  mysql-data:
